# Starter pipeline

# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

strategy:
  matrix:
    linux:
      imageName: "ubuntu-latest"
#    mac:
#      imageName: "macOS-latest"
#    windows:
#      imageName: "windows-latest"
  maxParallel: 3

pool:
  vmImage: $(imageName)

steps:

- task: Kubernetes@1
  inputs:
    connectionType: 'Kubernetes Service Connection'
    kubernetesServiceEndpoint: 'connectakslain'
    command: 'get'
    arguments: 'deployments -o wide'
    secretType: 'generic'
    outputFormat: 'none'
  name: 'kukube'

- task: Cache@2
  inputs:
    key: 'toto'
    path: '/home/vsts/ver'
    cacheHitVar: 'testcache'

# la partie ci dessous récupère le numéro de version dans la variable d'env "TESTVAR"
# déroulé du job : OK - trouver une solution pour stocker le résultat de la variable -> avec "cache"
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |   
      mkdir /home/vsts/ver
      TESTVAR=$(curl 'https://hub.docker.com/v2/repositories/simplonasa/azure_voting_app/tags' | jq '."results"[0]["name"]')
      echo "bli bla blou !"
      echo "$TESTVAR"|sed 's/^.//;s/.$//' > /home/vsts/ver/version
      echo "------------- blblblbl ------------"
      echo "RESULTAT :"
      cat /home/vsts/ver/version
      echo "---------- test kubectlk -----------"
      echo $KUKUBE_KUBECTLOUTPUT
  
- task: Cache@2
  inputs:
    key: 'toto'
    path: '/home/vsts/ver'
    cacheHitVar: 'testcache'