apiVersion: v1
kind: Secret
metadata:
  name: authsecret
  namespace: default
data:
  users: dXNlcjokYXByMSREQjBWUENhayRqUEtlaXE3R0djVUxKeFAzSjhkQVMwCgo=

# apiVersion: v1
# kind: Secret
# metadata:
#   name: authsecret
#   namespace: default
# data:
#   username: dXNlcg== # username: user
#   password: cGFzc3dvcmQ= # password: password